<a href="https://colab.research.google.com/github/ZodiaX1013/039_JaydeepGamit/blob/main/ML4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import Libraries
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Load dataset
digits = datasets.load_digits()
print(digits)
print(digits.data.shape)
print(digits.target.shape)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'frame': None, 'feature_names': ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', '

In [ ]:
# import the necessary module
from sklearn import metrics
from sklearn.model_selection import train_test_split

X = digits.data
Y = digits.target

# split data set into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.35, random_state = 100)

In [ ]:
# Create a Decision Tree Classifier (using Gini)
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 39, max_depth = 7, min_samples_leaf = 39)
clf_gini.fit(X_train, y_train)

# Predict the classes of test data
y_pred = clf_gini.predict(X_test)
print("Predicted values: ", y_pred)


Predicted values:  [9 9 0 2 4 5 4 4 9 2 4 5 7 5 9 6 1 9 5 4 8 7 6 6 6 7 0 2 7 3 0 9 3 9 9 5 3
 4 3 6 1 1 5 2 0 4 8 9 7 4 9 5 5 1 4 8 9 7 3 9 6 1 5 4 2 6 3 6 6 4 8 1 4 0
 6 6 2 9 0 1 1 3 3 1 1 4 8 5 0 4 1 7 0 0 8 1 4 0 7 5 4 0 9 3 4 5 7 1 1 5 5
 2 1 3 1 0 9 4 7 3 2 1 3 6 0 7 0 7 5 0 7 6 0 1 8 4 0 7 4 1 9 5 0 8 9 0 8 0
 3 6 8 4 4 8 8 9 0 0 1 2 1 7 9 9 1 9 1 5 3 4 2 0 6 9 9 1 0 0 7 4 4 4 3 9 5
 3 4 9 1 1 2 4 7 7 2 7 1 0 1 3 8 6 9 9 0 3 1 9 3 8 0 4 8 6 2 9 2 2 6 4 1 4
 4 2 3 0 7 1 7 1 4 1 0 9 0 5 0 7 7 4 0 2 4 0 8 2 1 4 3 7 0 2 1 5 1 2 4 4 0
 5 9 3 9 2 2 0 4 7 9 4 0 2 4 8 7 0 9 1 0 7 9 6 0 5 0 9 6 7 7 4 2 7 1 0 4 1
 9 6 4 1 7 9 9 7 8 1 1 0 2 5 9 6 9 3 9 0 7 3 0 7 8 4 5 7 4 4 8 4 0 6 6 4 5
 4 5 1 6 1 7 3 9 7 9 4 7 8 1 9 2 5 7 6 6 3 4 4 4 6 7 3 3 4 4 1 6 1 2 0 8 3
 5 8 4 4 6 4 8 4 7 4 5 8 9 4 4 3 2 4 7 3 4 9 3 5 7 4 2 9 1 8 8 5 1 8 0 8 2
 4 6 1 5 4 4 9 2 4 9 2 7 0 7 7 7 1 4 0 9 3 8 0 9 9 8 4 0 4 0 0 4 4 1 4 0 8
 6 4 4 4 9 4 3 6 4 4 1 9 7 1 1 5 1 7 7 0 5 9 1 9 6 3 0 4 5 1 9 1 0 0 7 9 3
 4 0 1

In [ ]:
# Model Accuracy
print("Confusion Matrix: ", metrics.confusion_matrix(y_test, y_pred))
print ("Accuracy: ", metrics.accuracy_score(y_test,y_pred) * 100)
print("Report: ", metrics.classification_report(y_test, y_pred))

Confusion Matrix:  [[66  0  1  0  1  0  0  0  1  1]
 [ 0 40  0  0  9  0  0  0  2 10]
 [ 1 22 35  5  4  0  0  2  0  0]
 [ 0  6  0 38  0  0  0  6  3  6]
 [ 2  3  0  0 61  0  0  1  0  2]
 [ 3  1  0  0  1 47  0  0  0 12]
 [ 3  2  0  0 13  0 46  0  0  0]
 [ 0  1  0  0  6  0  0 48  0  1]
 [ 1  5  2  1  2  0  0  4 32  6]
 [ 1  0  4  3  8  0  0  0  2 46]]
Accuracy:  72.97297297297297
Report:                precision    recall  f1-score   support

           0       0.86      0.94      0.90        70
           1       0.50      0.66      0.57        61
           2       0.83      0.51      0.63        69
           3       0.81      0.64      0.72        59
           4       0.58      0.88      0.70        69
           5       1.00      0.73      0.85        64
           6       1.00      0.72      0.84        64
           7       0.79      0.86      0.82        56
           8       0.80      0.60      0.69        53
           9       0.55      0.72      0.62        64

    accuracy    